### ISSUE TITLE
Underscores in branch names?

### ISSUE THREAD

**Issue by cooperl09** [geneontology/design_patterns#4]
I am curious why the GO is using underscores in the branch names?  If you enter the name without the underscore, it is not found in the term Quick Search.  This is a bit of an issue for our browser functionality http://browser.planteome.org/amigo/search/ontology?q=biological%20process
and for when working with GO terms in Protege.

None of the other classes in the GO are written with an underscore that I can see, at least.

For example: 
molecular_function
http://amigo.geneontology.org/amigo/term/GO:0003674

biological_process
http://amigo.geneontology.org/amigo/term/GO:0008150

cellular_component
http://amigo.geneontology.org/amigo/term/GO:0005575

Not sure if this is the correct repo for this.

**Comment by dosumis** [comment]
Historical reasons.  There was an attempt to change this a few years ago.  GO backed down following protests by resources that consume the GO - some of which apparently had hard-coded dependencies on these.  I suspect there is no appetite to revive this, but could ask if important to you.

> If you enter the name without the underscore, it is not found in the term Quick Search.

Should be found based on synonyms, surely?

**Comment by cooperl09** [comment]
Agreed that the AmiGO2 Quick Search works on the synonyms on the GO site, but does not on the Planteome browser:
http://browser.planteome.org/amigo/search/ontology?q=biological process

**Comment by dosumis** [comment]
> does not on the Planteome browser:

Probably should.  Pretty standard to allow search on name or synonym for any OBOish ontology.

**Comment by cmungall** [comment]
Sounds like an amigo ticket.

Although we should revisit the whole issue. We should announce the removal of the underscores and then do it some suitable grace period afterwards.
